### ISSUE TITLE
Handling un-set components

### ISSUE THREAD

**Issue by Ta1al** [promise/discord-bot-boilerplate#13] opened 2022-12-07 14:03 UTC
Currently, there is no way to handle message components that have not been set in the [cache Map](https://github.com/promise/discord-bot-boilerplate/blob/375eb41c50e62c8e063c0eb8576dcdb4a13aab95/src/handlers/interactions/components.ts#L38).

**Comment by promise** [comment] 2022-12-07 18:37
do you mean as a fallback response [here](https://github.com/promise/discord-bot-boilerplate/blob/375eb41c50e62c8e063c0eb8576dcdb4a13aab95/src/handlers/interactions/components.ts#L44)?

**Comment by Ta1al** [comment] 2022-12-08 04:10
Yes. For example, the permanent buttons you may click to get roles or something will not be set in the cache Map after the bot restarts, but the buttons still need to function somehow.

**Comment by promise** [comment] 2022-12-08 06:04
The permanent buttons should be set on startup then, just have it be a static custom ID, like "give_role:12345678".

what's your intended use case for this though?

**Comment by Ta1al** [comment] 2022-12-08 11:42
https://github.com/biaw/tickets/blob/main/src/commands/components/index.ts

**Comment by promise** [comment] 2022-12-08 12:42
intended behaviour is to set the static components on startup, how you want to do it is based on the use case.

my thought for the ticket bot was to set the component in some ticket handler. I'm assuming you need more code for tickets to handle everything so having it all in a ticket handler would be nice. Then just set the components whenever the file is loaded and make it persistent. https://github.com/promise/discord-bot-boilerplate/blob/c0dcbf6d44e43baa787794ec2ea9e7655312f575/src/handlers/interactions/components.ts#L6

e.g. a close ticket button could be as simple as `components.set("close_ticket", { ..., persistent: true, execute(interaction) { /* use the channel ID to find the ticket and close it */ } })` in some form of ticket handler. you need to send the component in the ticket somewhere so also setting it in the same file as where you're sending it would be ideal, so it's easy to find back to as well.

**Closed by promise** 2022-12-08 12:42 UTC
